---
title: "Análisis de COMPAS como predictor sesgado"
output: html_notebook
---

**Ignacia Aguilera, Camilo Ramírez, Sebastián Zapata** - ***Grupo 16***<br>
Curso CC5206 Introducción a la Minería de Datos<br>
Profesores: Felipe Bravo, Bárbara Poblete<br>
Facultad de Ciencias Físicas y Matemáticas, Universidad de Chile

# Introducción y motivación

Este informe se enmarca en el curso de Introducción a la Minería de Datos (CC5206) de la Universidad de Chile, para documentar el hito inicial (1) del proyecto minería de datos sobre el dataset asociado a COMPAS de [Northpointe](https://www.northpointe.com/) generado por [ProPublica](https://www.propublica.org/).

COMPAS es el acrónimo de *Correctional Offender Management Profiling for Alternative Sanctions*, que es traducible como "Gestión de perfiles de reos penitenciarios para penas alternativas" y corresponde a un algoritmo que busca predecir la probabilidad de reincidencia de un criminal al asignarle un puntaje (*score*) que representa la misma ([se puede encontrar su documentación aquí](https://assets.documentcloud.org/documents/2840784/Practitioner-s-Guide-to-COMPAS-Core.pdf)). Este método pertenece a la familia de algoritmos de evaluación de riesgo penitenciario (*risk assesment*) y se ha utilizado en diversas cortes de Estados Unidos como insumo para los jueces en la determinación del otorgamiento de libertad condicional a los imputados por algún delito.Esto responde a la necesidad de ese país de doscongestionar sus prisiones de forma eficiente. Es importante distinguir que este algoritmo no fue diseñado ni se ha utilizado para determinar la culpabilidad de alguna persona en un delito, ni para determinar una pena.

Un [estudio](https://www.propublica.org/article/machine-bias-risk-assessments-in-criminal-sentencing) realizado por ProPublica encontró un significativo sesgo racial en los resultados de puntaje COMPAS a desfavor de las personas afroamericanas a pesar que este atributo de las personas no se ingresaba como entrada al algoritmo. ProPublica además de publicar los resultados del estudio, publicó su [metdología](https://github.com/caitlinkuhlman/bpdmtutorial/blob/master/tutorial-COMPAS.ipynb) y un dataset generado a partir de la reccopilación de datos realizada por la agencia periodística. Las publicaciones se encuentran presente en el [repositorio de GitHub](https://github.com/propublica/compas-analysis) de ProPublica

# Problemática central

El objetivo de este proyecto es analizar y detectar los posibles sesgos que tenga COMPAS en un espectro más amplio de atributos además de verificar el sesgo racial descrito por el informe de ProPublica. Adicional a esto se busca determinar una forma de disminuir los sesgos detectados o determinar la imposibilidad de realizar lo anterior.

Para cumplir este objetivo se trabaja con el dataset principal publicado en el repositorio contenido en el fichero ```compas.db``` que corresponde a una base de datos de sqlite3. Esta se importa en R y utilizando esta herramienta, se hace un análisis de datos, eventualmente una limpieza y reducción de atributos para comenzar a analizar correlaciones que se puedan encontrar, los atributos que se consideran de interés corresponden a la etnia (raza) y género de las personas. En base a correlaciones de interés encontradas, se aplicarán herramientas de minería de datos más sofisticadas en los próximos hitos del proyecto.

# Exploración de datos

A modo de hacer el informe replicable, se deja explícito el código fuente utilizado. Para trabajar con ```compas.db``` se comienza importando las librerías requeridas, importando el fichero de la base de datos a través de una clase de SQL manejable por R para posteriormente extraer los dataframes del mismo.
```{r, results="hide"}
library(RSQLite)

filename <- "compas.db"
sqlite.driver <- dbDriver("SQLite")
db <- dbConnect(sqlite.driver, dbname = filename)

casearrest    <- dbReadTable(db,"casearrest")
charge        <- dbReadTable(db,"charge")
compas        <- dbReadTable(db,"compas")
jailhistory   <- dbReadTable(db,"jailhistory")
prisonhistory <- dbReadTable(db,"prisonhistory")
summary       <- dbReadTable(db,"summary")
people        <- dbReadTable(db,"people")
```